sources:
  - name: enzyme-vault
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/{env.API_KEY}/subgraphs/id/5fQN1uMK6uEswACUmN7HmvdMr3QLRhYDBrX8GngbR2Tn

documents:
  - ./queries.graphql